// Go to Manage Setting/System Go to Global Pipeline Libraries section give name & repo url where .groovy or shared library files are kept.
// By default it takes vars folder in settings.

@Library('shared-library') _

// @Library('shared-library') filename.groovy

pipeline {
    
    agent any 
    
    stages {


        stage('Call from Share Library'){
            steps{
                scriptFun()
            }
        }

        stage('Call from Share Library with custom value'){
            steps{
                scriptRepoName("varun@varun","20")
            }
        }

        stage('Call from Share Library with any arguments 1-2-3 or many'){
            steps{
                customPara(name:"varun", surname:"sonavni")
            }
        }



        stage('pipeline step'){
            steps{
                script{
                    sh '''
                    echo 'In jenkins file'
                    
                    '''
                }
            }
        }

        }
    }

