// Go to Manage Setting/System Go to Global Pipeline Libraries section give name & repo url where .groovy or shared library files are kept.
// By default it takes vars folder in settings.

@Library('shared-library') _

// @Library('shared-library') filename.groovy

pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {


        stage('Call from Share Library'){
            steps{
                scriptFun()
            }
        }

        stage('Call from Share Library with custom value'){
            steps{
                scriptRepoName("varun@varun")
            }
        }


        stage('pipeline step'){
            steps{
                script{
                    sh '''
                    echo 'In jenkins file'
                    
                    '''
                }
            }
        }

        }
    }

