pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'In jenkins file'
                    
                    '''
                }
            }
        }

        }
    }

